[engine]
helper_binaries_dir = ["/snap/m0x41-podman/current/usr/libexec/podman", "/snap/m0x41-podman/current/usr/lib/podman", "/snap/m0x41-podman/current/usr/bin"]
conmon_path = ["/snap/m0x41-podman/current/usr/bin/conmon"]
cgroup_manager = "systemd"
events_logger = "file"

[engine.runtimes]
crun = ["/snap/m0x41-podman/current/usr/bin/crun"]

[network]
network_backend = "netavark"
netavark_path = "/snap/m0x41-podman/current/usr/lib/podman/netavark"
default_rootless_network_cmd = "slirp4netns"
